version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nest-api
    volumes:
     - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: